USE sales_analytics;

--------------------------------------------------
-- 1. Total Revenue
-- What is the total revenue generated by the company?
--------------------------------------------------

SELECT 
SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id;


--------------------------------------------------
-- 2. Revenue by Product Category
-- Which product categories generate the most revenue?
--------------------------------------------------

SELECT 
p.category,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;


--------------------------------------------------
-- 3. Top 10 Products by Revenue
--------------------------------------------------

SELECT 
p.product_name,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 10;


--------------------------------------------------
-- 4. Top Retailers by Revenue
--------------------------------------------------

SELECT 
r.retailer_name,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN retailers r ON o.retailer_id = r.retailer_id
JOIN products p ON o.product_id = p.product_id
GROUP BY r.retailer_name
ORDER BY revenue DESC;


--------------------------------------------------
-- 5. Revenue by Supplier
--------------------------------------------------

SELECT 
s.supplier_name,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
JOIN suppliers s ON p.supplier_id = s.supplier_id
GROUP BY s.supplier_name
ORDER BY revenue DESC;


--------------------------------------------------
-- 6. Revenue by Region
--------------------------------------------------

SELECT 
rg.region_name,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN retailers r ON o.retailer_id = r.retailer_id
JOIN regions rg ON r.region_id = rg.region_id
JOIN products p ON o.product_id = p.product_id
GROUP BY rg.region_name
ORDER BY revenue DESC;


--------------------------------------------------
-- 7. Average Order Value
--------------------------------------------------

SELECT 
AVG(p.price * o.quantity) AS average_order_value
FROM orders o
JOIN products p ON o.product_id = p.product_id;


--------------------------------------------------
-- 8. Monthly Revenue Trend
--------------------------------------------------

SELECT 
DATE_FORMAT(o.order_date,'%Y-%m') AS month,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY month
ORDER BY month;


--------------------------------------------------
-- 9. Total Units Sold by Category
--------------------------------------------------

SELECT 
p.category,
SUM(o.quantity) AS units_sold
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY units_sold DESC;


--------------------------------------------------
-- 10. Most Popular Products (by quantity)
--------------------------------------------------

SELECT 
p.product_name,
SUM(o.quantity) AS units_sold
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY units_sold DESC
LIMIT 10;


--------------------------------------------------
-- 11. Supplier Product Count
--------------------------------------------------

SELECT 
s.supplier_name,
COUNT(p.product_id) AS number_of_products
FROM products p
JOIN suppliers s ON p.supplier_id = s.supplier_id
GROUP BY s.supplier_name
ORDER BY number_of_products DESC;


--------------------------------------------------
-- 12. Retailers Order Count
--------------------------------------------------

SELECT 
r.retailer_name,
COUNT(o.order_id) AS orders_count
FROM orders o
JOIN retailers r ON o.retailer_id = r.retailer_id
GROUP BY r.retailer_name
ORDER BY orders_count DESC;


--------------------------------------------------
-- 13. Revenue per Retailer per Category
--------------------------------------------------

SELECT 
r.retailer_name,
p.category,
SUM(p.
price * o.quantity) AS revenue
FROM orders o
JOIN retailers r ON o.retailer_id = r.retailer_id
JOIN products p ON o.product_id = p.product_id
GROUP BY r.retailer_name, p.category
ORDER BY revenue DESC;


--------------------------------------------------
-- 14. Highest Value Orders
--------------------------------------------------

SELECT 
o.order_id,
r.retailer_name,
p.product_name,
(p.price * o.quantity) AS order_value
FROM orders o
JOIN retailers r ON o.retailer_id = r.retailer_id
JOIN products p ON o.product_id = p.product_id
ORDER BY order_value DESC
LIMIT 10;


--------------------------------------------------
-- 15. Yearly Revenue
--------------------------------------------------

SELECT 
YEAR(o.order_date) AS year,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY year
ORDER BY year;


--------------------------------------------------
-- 16. Average Quantity per Order
--------------------------------------------------

SELECT 
AVG(quantity) AS avg_quantity
FROM orders;


--------------------------------------------------
-- 17. Product Price Distribution
--------------------------------------------------

SELECT 
category,
MIN(price) AS min_price,
MAX(price) AS max_price,
AVG(price) AS avg_price
FROM products
GROUP BY category;


--------------------------------------------------
-- 18. Retailers by Units Purchased
--------------------------------------------------

SELECT 
r.retailer_name,
SUM(o.quantity) AS total_units
FROM orders o
JOIN retailers r ON o.retailer_id = r.retailer_id
GROUP BY r.retailer_name
ORDER BY total_units DESC;


--------------------------------------------------
-- 19. Supplier Revenue Contribution
--------------------------------------------------

SELECT 
s.supplier_name,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
JOIN suppliers s ON p.supplier_id = s.supplier_id
GROUP BY s.supplier_name
ORDER BY revenue DESC;


--------------------------------------------------
-- 20. Top Product Category per Region
--------------------------------------------------

SELECT 
rg.region_name,
p.category,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN retailers r ON o.retailer_id = r.retailer_id
JOIN regions rg ON r.region_id = rg.region_id
JOIN products p ON o.product_id = p.product_id
GROUP BY rg.region_name, p.category
ORDER BY rg.region_name, revenue DESC;